
services:
  dynamo:
    container_name: local-dynamodb
    image: amazon/dynamodb-local
    networks:
      - local-dynamodb
    ports:
      - "8000:8000"
    volumes:
      - dynamodata:/home/dynamodblocal
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."

  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin
    networks:
      - local-dynamodb
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: http://host.docker.internal:8000
    depends_on:
      - dynamo

networks:
  local-dynamodb:
    name: local-dynamodb

volumes:
  dynamodata: {}